name: truemanradio
description: Dungeon master's gay website with radio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.1.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  provider: ^6.0.3
  mini_music_visualizer: ^1.0.2
  audioplayers: ^1.0.0-rc.4
  video_player: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.svg
    - assets/gym.jpg
    - assets/bg_GayWave.gay.mp4
    - assets/bg_GayWave.sadGay.mp4
    - assets/bg_GayWave.trueGay.mp4
    - assets/tracklist.json
