name: Telegram notification on push
on: push
jobs:
  build:
    name: Send Telegram message
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: "-1001664127726"
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} commited [${{github.sha}}](https://github.com/${{ github.repository }}/commit/${{github.sha}}):
            ${{ github.event.commits[0].message }}
